# Generated by Django 3.1.5 on 2021-01-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='color_palette',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='dots',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
