# Generated by Django 3.1.5 on 2021-01-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('pics', '0002_auto_20210127_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='categories',
            field=models.ManyToManyField(related_name='pics', to='categories.Category'),
        ),
    ]
