# Generated by Django 3.1.5 on 2021-01-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0003_pic_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='artist',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_pic', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
