# Generated by Django 3.1.5 on 2021-01-27 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0004_pic_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
