# Generated by Django 3.1.6 on 2021-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_pic_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='color_palette',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pic',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='dots',
            field=models.TextField(max_length=3100),
        ),
    ]
